# Generated by Django 4.1.5 on 2023-02-02 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('drafts', 'Черновик'), ('open', 'Открыта'), ('close', 'Закрыта')], default='drafts', max_length=6),
        ),
    ]
